### ISSUE TITLE
can't create app

### ISSUE THREAD

**Issue by transtone** [mtkennerly/shawl#11]
`shawl add --name myapp -- 'D:\soft\myApp.exe'`
```cmd
[ERROR] Failed to create the service. Error code: 1072.
[ERROR] SC stdout:
[SC] OpenSCManager ʧ�� 1072:

�ܾ����ʡ�


[ERROR] SC stderr:

```

**Comment by mtkennerly** [comment]
Hmm, from what I can tell, error 1072 sounds related to not being able to delete a service, which is odd in this context if it doesn't already exist. I'm not sure what's going on, but here are some questions to try to narrow it down:

* What version of Windows are you using?
* What console are you using?
* Are you running the console as admin?
* Does the Windows services list show anything with the name `myapp` already?

**Comment by mtkennerly** [comment]
I'm closing this since I don't have enough info to take action, but I'll be happy to look into this if you can provide some more details.
