### ISSUE TITLE
Service not receiving stop signal at system shutdown

### ISSUE THREAD

**Issue by Mikedevops-NL** [mtkennerly/shawl#12]
Hello Mtkennerly,

Let me start off by saying that I like your project very much because it saved me a lot of time!
But still I ran in to a problem.
When the system is shutting down my service stops, but in the logs I don't see a stop signal.
When I stop my service trough windows service manager the stop signal is getting logged and my app starts the graceful shutdown process like expected.

Maybe you can point me in the right direction because I cant seem to figure out what is going wrong?

**Comment by mtkennerly** [comment]
Hi! Thanks for bringing this up. I think this is because Shawl implements `ServiceControl::Stop`, but not `ServiceControl::Shutdown`. I'll test it out, and if that's the reason, then I'll make a release to fix it.

**Comment by Mikedevops-NL** [comment]
Thanks for your quick response.
I will keep an eye on your project for updates

**Comment by mtkennerly** [comment]
This is now fixed in the latest release, [v1.0.0](https://github.com/mtkennerly/shawl/releases/tag/v1.0.0).

**Comment by Mikedevops-NL** [comment]
it now works as expected, thank you very much.
