### ISSUE TITLE
adding version to shawl.exe properties

### ISSUE THREAD

**Issue by dreamflow** [mtkennerly/shawl#14]
hi , i'm a user of shawl.exe .

could please the version of shawl be added to the shawl.exe properties
like on the picture below .
this would make it easier to manually and programatically
see the different shawl.exe versions on different machines ,
where shawl is installed on .

![shawl exe properties with version](https://user-images.githubusercontent.com/13277579/124576506-a9a55e80-de4c-11eb-8b34-25b461d8ad24.png)

**Comment by mtkennerly** [comment]
Sure, that sounds like a good idea :+1:

**Comment by mklinke** [comment]
Looks like it's not possible to include those properties in the exectuable while this is still open: https://github.com/rust-lang/rfcs/issues/721

**Comment by dgellow** [comment]
@mklinke From what I see that can be done using the cargo build script [embed-resource](https://github.com/nabijaczleweli/rust-embed-resource).`

**Comment by mtkennerly** [comment]
I went with [winres](https://crates.io/crates/winres) since it seemed more straightforward:

> ![image](https://user-images.githubusercontent.com/4934192/149840294-4eae92be-452e-4e76-b5ad-325822205b6a.png)

**Comment by dgellow** [comment]
Great :)

**Comment by dreamflow** [comment]
thank you @mtkennerly for implementing this feature
and thank you all others in this thread .

i'm already making use of this feature in my application
and can confirm that it's super easy now to programatically
read the shawl.exe version .

for those interessed , i read the shawl.exe version
with a one-liner in AutoIt
`FileGetVersion( '...path_to...\shawl.exe' , 'ProductVersion' )`
