### ISSUE TITLE
is support jar package?

### ISSUE THREAD

**Issue by wushikj** [mtkennerly/shawl#15]

**Comment by mtkennerly** [comment]
Yes! If you have a self-executing JAR, then Shawl can run it just like any other program. For other JARs, you can configure Shawl to run `java -jar your-app.jar`.

**Comment by rustbomb** [comment]
I use this command ,is not work:

```
PS C:\temp\java_demo> .\shawl.exe run --name a --cwd C:\temp\ java_demo "java -jar scheduler-demo-2.1.0.RELEASE.jar"
```

report:
error: Found argument 'java -jar scheduler-demo-2.1.0.RELEASE.jar' which wasn't expected, or isn't valid in this context

**Comment by mtkennerly** [comment]
`shawl run` isn't meant to be used directly from the console like that. You would configure a service that executes the `shawl run` command instead. If you try to run it in a normal interactive user session, it will fail.
