### ISSUE TITLE
Service fails to start at AllocConsole

### ISSUE THREAD

**Issue by adiroiban** [mtkennerly/shawl#28]
I am reporting this error here just in the case in which someone else hit it.

```
[ERROR] winapi AllocConsole failed with code 31
```

From the [Windows API docs](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-)

ERROR_GEN_FAILURE 31 (0x1F) A device attached to the system is not functioning.

------------

I am not sure why this stopped working.
The shawl used to work, I did a Windows OS update and now it no longer works.

I am still troubleshooting this.

Most probably this is not an shawl error... and just a  WIndows setup.

**Comment by mtkennerly** [comment]
Hmm, I'm not able to reproduce this on Windows 11:

> Edition: Windows 11 Home
> Version: 22H2
> Installed on: 2023-02-15
> OS build: 22621.1555
> Experience: Windows Feature Experience Pack 1000.22640.1000.0

Could you share your OS version?

**Comment by mtkennerly** [comment]
Are all of your VMs using the same version of Shawl (latest is v1.1.1)?

**Comment by adiroiban** [comment]
Hi. Sorry for the late reply.
It was very strange.

I had the exact same version installed twice.
One was starting just fine, the other was failing.


Thanks for closing this ticket.
I hope I will not hit this issue again :)
