### ISSUE TITLE
Not able to create service with powershell

### ISSUE THREAD

**Issue by mlenz968** [mtkennerly/shawl#30]
I want to start a powershell script with shawl but as soon as I have powershell on the shawl command line the Windows service is broken.
Of course my original service registration has more arguments but I could reduce it to this simple service registration to reproduce the problem:
`shawl add --name PS_Test -- "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -File service_master.ps1"`
or even
`shawl add --name PS_Test -- powershell -File service_master.ps1`

If I try to open the service properties in the Windows Services I get an error message `The system cannot find the file specified.`

Also the service description only contains an error message: `<Failed to Read Description. Error Code: 2 >`

Does anybody have an idea what could be the root cause and how to solve it?

**Comment by mtkennerly** [comment]
> `shawl add --name PS_Test -- "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -File service_master.ps1"`

There are a couple of problems with this command:

* You only need quotes around individual arguments (with spaces). The exe and arguments don't need to all be grouped together in a single pair of quotes.
* `service_master.ps1` is a relative path, but you haven't specified a `--cwd`, so it'll look for the script in whatever default working directory Windows assigns to the service. You probably want to either set `--cwd` or use an absolute path to the script.

For example, if the script is in `C:\scripts\service_master.ps1`, then you could try one of these:

* `shawl add --name PS_Test -- powershell -File C:\scripts\service_master.ps1`
* `shawl add --name PS_Test --cwd C:\scripts -- powershell -File service_master.ps1`

**Comment by mlenz968** [comment]
I also tried the following variants but they all had the same problem:

- `shawl add --name PS_Test --cwd "C:\service_test" -- powershell -File "service-master.ps1"`
- `shawl add --name PS_Test --cwd C:\service_test -- powershell -File service-master.ps1`
- `shawl add --name PS_Test -- powershell -File "C:\service_test\service-master.ps1"`
- `shawl add --name PS_Test -- powershell -File C:\service_test\service-master.ps1`

**Comment by mtkennerly** [comment]
Yeah, that's really weird. Unfortunately, I'm not able to reproduce it. This worked for me on Windows 11 with PowerShell 5.1.22621.1778:

* C:\tmp\script.ps1:

  ```
  Add-Content script.txt "`ntest"
  ```
* `shawl.exe add --name PS_Test --cwd C:\tmp -- powershell -File script.ps1`
* `sc start PS_Test`
* C:\tmp\script.txt:

  ```
  test
  ```

I was also able to just do `shawl.exe add --name PS_Test --cwd C:\tmp -- script.ps1` without specifically referencing `powershell`. Does that work for you, so you can avoid the symbolic link?
