### ISSUE TITLE
Log rotation failed

### ISSUE THREAD

**Issue by Luokun2016** [mtkennerly/shawl#31]
**shawl version**
v1.1.1 or v1.2.0

**Create Service Commamd:**
`sc create south-connector binPath= "\"C:\Program Files\xx\shawl.exe\" run  --log-dir \"C:\Program Files\xx\south-connector\logs\" --name south-connector --cwd \"C:\Program Files\xx\south-connector\" -- south-connector.exe" start= auto `

**Service Info:**
![image](https://github.com/mtkennerly/shawl/assets/24650960/e20cd754-2ebc-456f-ada8-49ca607ea634)

The Criterion for rotating log files works, but cleanup does not.
![image](https://github.com/mtkennerly/shawl/assets/24650960/e9ac7d07-88b4-4021-98cc-8f67b3b53e7f)

**Windows Version**
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎10/‎8
操作系统版本	22621.1992
体验	Windows Feature Experience Pack 1000.22644.1000.0

**Comment by mtkennerly** [comment]
Hi! Thanks for reporting this.

I can't seem to reproduce it so far. Oddly, your log files rotate at 1,001 KB, but it should happen at 2,049 KB. I see mine rotate at 2,049 KB and then get deleted when there would be more than three files.

Since your files are about half the size of mine, I wonder if you would have twice as many files. Does it ever go up to 10 log files if you let it keep running? Or does it max out at 7 like in the screenshot?

I didn't see anything relevant in the changelog for `flexi_logger`, but I could try updating that dependency just in case it helps.

**Comment by Luokun2016** [comment]
> Hi! Thanks for reporting this.
> 
> I can't seem to reproduce it so far. Oddly, your log files rotate at 1,001 KB, but it should happen at 2,049 KB. I see mine rotate at 2,049 KB and then get deleted when there would be more than three files.
> 
> Since your files are about half the size of mine, I wonder if you would have twice as many files. Does it ever go up to 10 log files if you let it keep running? Or does it max out at 7 like in the screenshot?
> 
> I didn't see anything relevant in the changelog for `flexi_logger`, but I could try updating that dependency just in case it helps.

For a quick test, I set the **Rotate Size** to **1MB**.

After I upgraded flexi_logger to 0.25.5, it doesn't work properly in shawl. 
The strange thing is that the prepare_logging method works fine when unit testing, and old files can be cleaned up normally.

**Comment by Luokun2016** [comment]
`"C:\Program Files\xx\shawl.exe" run  --log-dir "C:\Program Files\xx\south-connector\logs" --name south-connector --cwd "C:\Program Files\xx\south-connector" -- south-connector.exe`

`2023-08-07 09:05:38 [DEBUG] Cli { sub: Run { common: CommonOpts { pass: None, restart: false, no_restart: false, restart_if: [], restart_if_not: [], stop_timeout: None, no_log: false, no_log_cmd: false, log_dir: Some("\\\\?\\C:\\Program Files\\xx\\south-connector\\logs"), pass_start_args: false, env: [], path: [], command: ["south-connector.exe"] }, cwd: Some("C:\\Program Files\\xx\\south-connector"), name: "south-connector" } }`

log_dir parse as  **Some("\\\\?\\C:\\Program Files\\xx\\south-connector\\logs")**

**Comment by Luokun2016** [comment]
**fix changes** @mtkennerly 
![image](https://github.com/mtkennerly/shawl/assets/24650960/0cd5c09e-6079-4c10-9cd7-ccff9152ea1d)

**Comment by mtkennerly** [comment]
Fix from https://github.com/mtkennerly/shawl/pull/33 is now available in [v1.2.1](https://github.com/mtkennerly/shawl/releases/tag/v1.2.1) 🎉

**Comment by whichwit** [comment]
Do we need to recreate the service or simply replace the executable?

**Comment by Luokun2016** [comment]
> Do we need to recreate the service or simply replace the executable?
Just replace the executable.
