### ISSUE TITLE
Feature request: Start process with specified priority

### ISSUE THREAD

**Issue by Bill-Stewart** [mtkennerly/shawl#35]
Cool project, thanks!

I think it would be a nice convenience feature to be able to specify the service executable's process priority; e.g.:

    shawl run --priority belownormal ...

**Comment by Bill-Stewart** [comment]
Actually, it would be more than just a convenience feature. If I use an intermediate application to spawn the service executable with a different priority, it appears that the `Ctrl+C` signal doesn't get sent to the spawned process. The result is that the spawned process stays running but the service is stopped. Being able to specify a process priority would fix this.

**Comment by mtkennerly** [comment]
This is now available in [v1.3.0](https://github.com/mtkennerly/shawl/releases/tag/v1.3.0) :)

**Comment by Bill-Stewart** [comment]
Excellent, thank you @mtkennerly!
