### ISSUE TITLE
I don't get log file per service

### ISSUE THREAD

**Issue by janhoy** [mtkennerly/shawl#39]
Thanks for this project. I was finding NSSM buggy so I switched to this. Much faster and more stable.

I managed to place logs in a different folder. I run two services "s1" and "s2", and was expecting a log file for each, i.e. `shawl_for_s1.log` and `shawl_for_s2.log`. But instead I get one file `shawl_for_Shawl_rCURRENT.log`, which seems like a bug?

**Comment by mtkennerly** [comment]
Ah, I see the README doesn't mention `--name` in the example of creating a service by using `sc` directly. I'll add that to the example.

**Comment by janhoy** [comment]
Yes, I create with `sc`. So when adding `--name %SERVICE_NAME%` it works. Could not shawl sniff the service name from its environment somehow to default to something? Anyway, I'm happy, closing.
