### ISSUE TITLE
Improve documentation in README

### ISSUE THREAD

**Issue by janhoy** [mtkennerly/shawl#40]
README does not mention `--env`, `--cwd` or `--log-dir`. I needed all three and had to search through github issues to find them, since I'm not on Windows myself, but still needed to plan for using the tool on a remote server before I downloaded and installed it.

I found them all by `shawl help run` but perhaps that info could be added to the github site somewhere (not necessarily on README)?

**Comment by mtkennerly** [comment]
That's a fair point about not being on Windows yourself. I've added an auto-generated file with the full help text: https://github.com/mtkennerly/shawl/blob/master/docs/cli.md
