### ISSUE TITLE
Integrate with Window Service Recovery functions for "failure" not only for "stop with error"

### ISSUE THREAD

**Issue by adiroiban** [mtkennerly/shawl#45]
Exit the service with a failure when the process exit code  is not 0 and  using  --no-restart

It would help to somehow forward the wrapped process exit code when configured with `--no-restart`

In this way you can use the Windows Serive "Recovery" helpers

![image](https://github.com/mtkennerly/shawl/assets/204609/b405f87c-1b0b-4ec8-bd6e-4b5d8bbb39c2)

----

To reproduce, I have this shawl run

```
C:\test\shawl.exe run --name shawl-test --no-restart  --cwd "\\?\C:\test" --log-dir "\\?\C:\test" -- ping -n 1000 127.0.0.1
```

Start the service. It will start ok and and in the logs you will see

```
2023-12-07 18:48:01 [DEBUG] Entering main service loop
2023-12-07 18:48:01 [INFO] Launching command
2023-12-07 18:48:01 [DEBUG] stdout: "Pinging 127.0.0.1 with 32 bytes of data:"
2023-12-07 18:48:01 [DEBUG] stdout: "Reply from 127.0.0.1: bytes=32 time<1ms TTL=128"
2023-12-07 18:48:02 [DEBUG] stdout: "Reply from 127.0.0.1: bytes=32 time<1ms TTL=128"
```

Open Windows Task Manager and end the TCP Ping process.

In the logs, you will see

```
2023-12-07 18:49:06 [DEBUG] stdout: "Reply from 127.0.0.1: bytes=32 time<1ms TTL=128"
2023-12-07 18:49:07 [DEBUG] stdout: "Reply from 127.0.0.1: bytes=32 time<1ms TTL=128"
2023-12-07 18:49:08 [INFO] Command exited with code 1
2023-12-07 18:49:08 [DEBUG] Exited main service loop
2023-12-07 18:49:08 [DEBUG] Finished successfully
```

If you check Windows Event logs, in the "Windows Logs -> System" section , you will see info event ID 7036 "The shawl-test service entered the stopped state."

---------

If instead of ending the TCP ping process, you end the shawl-exe process, you will see error event ID

7031 "The shawl-test service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 60000 milliseconds: Restart the service."

----------

Expected result: If `--no-restart` is configured and wrapped process exit code is not 0, trigger a Windows Service failure.

Actual result: Even if the wrapped process exitcode is 1, the shawl Windows server is stopped like a normal succesfull stop

**Comment by adiroiban** [comment]
I think that the automatic process restart implemented in shawl is nice... but can lead to hiding some important bugs.

The process is restarted in the background ... with only a log in shawl log file.

But I guess most sysadmin are monitoring the Windows Service Event Log events.
And if you check the Windows Event Log, there is nothing to hint about the restarts.

**Comment by adiroiban** [comment]
So in Windows we have 3 service end conditions

* A - shawl.exe process exit code 0, and send a Win API stop service with succes event
* B - shawl.exe process exit code 0, and send a Win API stop service with error event
* C - shawl.exe process exit code non zero, without sending any  Win API service events

Condition A will never trigger any recovery action.

Condition B will only rigger the recovery if `Enable actions for stops with errors` is checked

Condition C is not currently supported in shawl ... it is only trigger if somehow shawl itself crashes.

---------

With the current code if we send Win API stop servie with error event and also end the shawl.exe process with non zero we might end up with the recovery action called twice.

-------

I am going to close this as I don't have a good enought solution for this.

The `Enable actions for stops with errors` can be a workaround.

If others need this functionality, we can reopen this and see how it can be done.

-----

Many thanks again for your excelent work.

**Comment by mtkennerly** [comment]
Thanks for the extra detail :+1:

For now, I've added a note to the README about how this works: https://github.com/mtkennerly/shawl#recovery
