### ISSUE TITLE
Does this support virtual service account?

### ISSUE THREAD

**Issue by netheril96** [mtkennerly/shawl#49]
nssm supports [virtual service account](https://www.1e.com/blogs/accounts-everywhere-part-1/) which allows each service to run as a different and limited user, just like the best practice on Linux. Does shawl support it too? I'm considering migrating but this is a must feature for me.

**Comment by mtkennerly** [comment]
Yes! I actually hadn't heard of these before, but I just tested it, and they work fine. Here's an example using the `shawl-child` test app from this repo:

```
shawl.exe add --name shawl -- C:\...\shawl-child.exe
sc config shawl obj= "NT SERVICE\shawl"
sc start shawl
sc stop shawl
```

When I add a log for the current username, it outputs `shawl`, whereas by default it would output `SYSTEM`.
