### ISSUE TITLE
Make it usable programmatically

### ISSUE THREAD

**Issue by giovannimirarchi420** [mtkennerly/shawl#51]
Hello!

I'm working on a personal project that aims to be cross-platform. This project involves the ability to install, start, and stop a daemon service on the user's machine. After some exploration, I discovered that Windows has limitations regarding running executables directly as services, which led me to tools like NSSM.

I then came across your crate, which seems very well-designed! However, I haven't been able to find a programmatic API for integration. This would eliminate the need for awkward workarounds like command calls or requiring the user to run cargo or your CLI directly.

Would implementing such an API be a good direction for the project? It would allow users to programmatically start the service, similar to the [service-manager-rs](https://github.com/chipsenkbeil/service-manager-rs) crate.

If this seems like a valuable addition and no one else takes the lead before I have the opportunity, I'd be happy to delve into the repository and potentially submit a pull request (PR).

Thanks,
Giovanni

**Comment by mtkennerly** [comment]
Hi! I'm potentially open to adding something like this, but I'd like to get a better idea of the problems you're facing with integrating it currently.

> This would eliminate the need for awkward workarounds like command calls

Could you clarify what you mean? The `shawl add` command is an optional convenience, but you can set up Shawl using something like that service-manager-rs crate as well. The service definition just has to invoke `shawl run`, but I don't see a way to eliminate that requirement.

> It would allow users to programmatically start the service, similar to the [service-manager-rs](https://github.com/chipsenkbeil/service-manager-rs) crate.

Shawl doesn't have any commands for starting/stopping services. A Shawl library could expose a function for constructing the `run` CLI to be configured in the service, but Shawl isn't really focused on service setup/orchestration (with the exception of the `add` command to streamline first-time setup).

You could do something like this currently:

```rust
manager.install(ServiceInstallCtx {
    label: "shawl".to_string(),
    program: PathBuf::from("C:/opt/shawl.exe"),
    args: vec![
        OsString::from("run"),
        OsString::from("--no-restart"),
        OsString::from("--"),
        OsString::from("C:/opt/wrapped-tool.exe")
    ],
    // ...
})?;
```

You would just need to bundle a copy of the Shawl executable and point the service to it. (Even in a hypothetical library mode, you would still need to pass in the location of a Shawl executable for the service to run.)

**Comment by giovannimirarchi420** [comment]
Hi again, thanks for getting back to me.

> This would eliminate the need for awkward workarounds like command calls

In this sentence I mean that I'd like to avoid something like:

```
    Command::new("/path/to/shawl.exe")
        .args(["your", "args"])
        .output()
        .expect("failed to execute process")

```
You're absolutely right, I could integrate your CLI into service-manager-rs (like you demonstrated) by including it in the current file system. However, as I mentioned before, I'd prefer to avoid this approach.

One alternative would be to bundle your `shawl.exe` executable directly into my program during the build process. This would then store it on the user's file system, eliminating the need for them to have shawl pre-installed. However, it would still introduce a dependency on having the executable included within my program.

My ideal scenario would be to simply import your crate as a library and utilize the same backend functions that power your CLI. This would allow me to integrate the service programmatically within my project, potentially making it valuable for other developers as well.

Thank you,
Giovanni

**Comment by mtkennerly** [comment]
> However, it would still introduce a dependency on having the executable included within my program.

Right, even if you were to use the same underlying functions that the CLI does, you'd still need a copy of the Shawl executable on the file system. The CLI assumes that that's the current executable:

https://github.com/mtkennerly/shawl/blob/70eb94ecbf183da4cd0423be0adef84bca1f7869/src/control.rs#L11-L15

...but in a library mode, you'd need to pass that path as an argument.

If there's no Shawl executable on the file system, then there won't be anything for Windows to launch as a service.

**Comment by giovannimirarchi420** [comment]
Thanks for the feedback! 
I understand that what I was originally asking for isn't feasible. 
I appreciate you taking the time to explain why.

Giovanni
