### ISSUE TITLE
Spaces in the Path to shawl.exe and service.exe does'nt work

### ISSUE THREAD

**Issue by thomasX** [mtkennerly/shawl#54]
if i try to create a Service with the following script:

`sc create my-app binPath= "C:\Program Files\mydir\shawl.exe run --name my-app -- C:\Program Files\mydir\ma-app.bat"`

when i try to start the service, i get the Error 2 : The system cannot find the file specified

if i create the service with the following script:
`sc create my-app binPath= "C:\Program Files\mydir\shawl.exe run --name my-app -- C:\ma-app.bat"`

everything is OK

**Comment by mtkennerly** [comment]
Hi! You can fix this by adding inner escaped quotes. This works for me in Command Prompt:

```
sc create my-app binPath= "\"C:\Program Files\mydir\shawl.exe\" run --name my-app -- \"C:\Program Files\mydir\ma-app.bat\""
```
