### ISSUE TITLE
How to add service in Windows; program with parameters

### ISSUE THREAD

**Issue by gosforth** [mtkennerly/shawl#56]
I think this command is wrong:

shawl add --name jBPM -- C:/jbpm/bin/standalone.bat -Dorg.kie.mail.session=java:/jbpmMailSession

What is the correct syntax?
Thanks for help

**Comment by mtkennerly** [comment]
Hi! That command looks okay to me. Are you getting an error message?

**Comment by gosforth** [comment]
Service/software is running but looks like the options are ignored.

**Comment by mtkennerly** [comment]
Could you share the Shawl log file for your service? It would be named `shawl_for_jBPM_rCURRENT.log`.

Does standalone.bat need to run from a particular working directory? You may want to try passing something like `--cwd C:/jbpm/bin` to Shawl.

**Comment by mtkennerly** [comment]
@gosforth Just following up; do you still need help with this?
