### ISSUE TITLE
Add prepend-path parameter

### ISSUE THREAD

**Issue by Sprinkle** [mtkennerly/shawl#57]
Would like to see an option added in addition to `--path` for allowing additional path to be ***prepended*** rather than appended.

The use case is that a service to be wrapped may spawn child process and want the path to search for executable to be different than the system path by giving search preference to a particular directory.

**Comment by mtkennerly** [comment]
Thanks for the suggestion! This is now  available in [v1.6.0](https://github.com/mtkennerly/shawl/releases/tag/v1.6.0) \:D

**Comment by Sprinkle** [comment]
Thanks for adding this so swiftly!
